# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2026.03.02-7-ge05c33a
_src_path: gh:scientific-python/cookie
backend: hatch
docs: zensical
email: kratsg@gmail.com
full_name: Giordon Stark
license: Apache
org: kratsg
project_name: stare
project_short_description: Python library and CLI for the CERN ATLAS Glance/Fence API
url: https://github.com/kratsg/stare
vcs: false
