"""Semantic string enums for Glance API fields.

Each public enum documents the known value set for a field.
All enums are exposed in their "lenient" form via the ``Lenient*`` type
aliases, which accept unknown strings gracefully (logging a warning)
rather than raising a validation error.
"""

from __future__ import annotations

import logging
from enum import Enum
from typing import Annotated, Any, TypeVar

from pydantic import BeforeValidator

_logger = logging.getLogger("stare")

_E = TypeVar("_E", bound="StrEnum")


class StrEnum(str, Enum):
    """Python 3.10-compatible string enum base (StrEnum was added in 3.11)."""


def _lenient(enum_cls: type[_E]) -> Any:
    """Return ``Annotated[EnumCls | str, BeforeValidator]`` for use in model fields.

    Unknown string values fall back to the raw string and log a warning.
    """

    def _validate(v: object) -> object:
        if not isinstance(v, str):
            return v
        try:
            return enum_cls(v)
        except ValueError:
            _logger.warning(
                "Unknown %s value %r — storing as raw string", enum_cls.__name__, v
            )
            return v

    return Annotated[enum_cls | str, BeforeValidator(_validate)]


class MeetingType(StrEnum):
    """Phase0 meeting role tags (used internally after flattening the 4 meeting lists)."""

    EOI = "eoi"
    EDITORIAL_BOARD_REQUEST = "editorial_board_request"
    PRE_APPROVAL = "pre_approval"
    APPROVAL = "approval"


# <AUTO-GENERATED-ENUMS:START>
class AnalysisStatus(StrEnum):
    """Auto-generated enum."""

    CREATED = "Created"
    ANALYSIS_CLOSED = "Analysis Closed"
    PHASE0_ACTIVE = "Phase 0 Active"
    PHASE0_CLOSED = "Phase 0 Closed"


class PaperStatus(StrEnum):
    """Auto-generated enum."""

    CREATED = "Not Started"
    ANALYSIS_CLOSED = "Closed"
    PHASE1_ACTIVE = "Phase 1 Active"
    PHASE1_CLOSED = "Phase 1 Closed"
    PHASE3_ACTIVE = "Phase 2 Active"
    PHASE3_CLOSED = "Phase 2 Closed"
    SUBMISSION_ACTIVE = "Publication Phase Active"
    SUBMISSION_CLOSED = "Completed"


class ConfnoteStatus(StrEnum):
    """Auto-generated enum."""

    CREATED = "Created"
    ANALYSIS_CLOSED = "Analysis Closed"
    PHASE1_ACTIVE = "Phase 1 Active"
    PHASE1_CLOSED = "Phase 1 Closed"


class AnalysisPhase0State(StrEnum):
    """Auto-generated enum."""

    NOT_STARTED = "Phase 0 Data"
    EOI_MEETING = "Expression of interest (EOI) meeting data"
    ANALYSIS_DEFINITION = "Analysis definition after EOI meeting"
    ANALYSIS_COORDINATORS_SELECTION = "Analysis contact and expert review selection"
    FIRST_ANALYSIS_DATA = "Analysis metadata"
    ANALYSIS_COORDINATORS_TIMELINE = "Analysis contacts' target date"
    SECOND_ANALYSIS_DATA = "Auxiliary metadata"
    INTERNAL_NOTE_EDITORS_DEFINITION = (
        "Internal note editors and contact editors appointment"
    )
    EDBOARD_REQUEST_MEETING_DATA = "Editorial Board request meeting and formation data"
    EDBOARD_MEETING_DATA = "Editorial Board meeting data"
    PRE_APPROVAL_MEETING_DATA = "Pre approval meeting data"
    PGC_SGC_CONTACT_SIGNOFF = "PGC or SGC pre approval sign-off"
    PUBLICATION_DRAFT = "Publication draft"
    APPROVAL_MEETING_DATA = "Approval meeting data"
    APPROVAL_ACCEPTANCE = "Approval acceptance"
    FINISHED = "Publications definition"
    PAPER_SKIP = "Skipped to Paper"
    CONF_SKIP = "Skipped to CONF Note"
    PUB_SKIP = "Skipped to PUB Note"
    PAPER_CONTACT_EDITORS_DEFINITION = (
        "Contact editors and Editorial Board appointment (skipped to Paper)"
    )
    CONF_CONTACT_EDITORS_DEFINITION = (
        "Contact editors and Editorial Board appointment (skipped to CONF note)"
    )
    PUB_CONTACT_EDITORS_DEFINITION = "Contact editors appointment (skipped to PUB note)"


class PaperPhase1State(StrEnum):
    """Auto-generated enum."""

    NOT_STARTED = "Phase 1 Data"
    STARTED = "Editorial Board"
    APPROVED_BY_REVIEWER = "Analysis Review"
    LGP_APPROVED = "Editorial Board Draft Sign-off"
    REVIEW_CLOSED = "Draft 1 Released to ATLAS"
    FINISHED = "Phase Closed"


class PaperPhase2State(StrEnum):
    """Auto-generated enum."""

    STARTED = "Phase 2 Data"
    FINAL_REVIEW_CLOSED = "Draft 2 Approval Process"
    UPDATE_EDBOARD = "Revised Draft Final Sign-off by Editorial Board Chair"
    UPDATED_PUBCOMM = (
        "Revised Draft Final Sign-off by Publication Committee Chair or Deputy"
    )
    UPDATED_SPOKESPERSONDATE = "Final Sign-off by Spokesperson or Deputy"
    FINISHED = "Phase Closed"


class PaperSubmissionState(StrEnum):
    """Auto-generated enum."""

    NOT_STARTED = "Publication Phase Launch"
    STARTED = "Tarball Receiving"
    TARBALL_RECEIVED = "CERN and ATLAS Collection"
    SUBMITTED_TO_ARXIV = "Journal Submission"
    SUBMITTED_TO_JOURNAL = "Journal Reports Receiving"
    JOURNAL_REPORT_RECEIVED = "Journal Reports Answering"
    JOURNAL_REPORT_ANSWERED = "Journal Acceptance"
    ACCEPTED_BY_JOURNAL = "Proofs Receiving"
    PROOF_RECEIVED = "Proofs Answering"
    PROOF_ANSWERED = "Online Publication"
    PUBLISHED_ONLINE = "Final ArXiv Replacement"
    ERRATUM_REQUESTED = "Erratum Submission"
    ERRATUM_SUBMITTED = "Erratum Acceptance"
    FINAL_ARXIV_REPLACED = "Paper Finish"
    FINISHED = "Submission Closed"


class ConfnotePhase1State(StrEnum):
    """Auto-generated enum."""

    NOT_STARTED = "Phase 1 Data"
    STARTED = "Editorial Board"
    APPROVED_BY_REVIEWER = "Analysis Review"
    LGP_APPROVED = "Editorial Board Draft Sign-off"
    PHASE1_ACTIVE = "Phase 1 Active"
    SECOND_SIGNED = "CONF Release"
    ATLAS_APPROVED = "Final Sign-off"
    EDBOARDSIGNOFF = "Editorial Board Draft Sign-off"
    DRAFT_RELEASED = "ATLAS Review Organized by Physics Coordinator"
    REVIEW_CLOSED = "Draft 1 Released to ATLAS"
    FINISHED = "Phase Closed"


# <AUTO-GENERATED-ENUMS:END>


class CollisionType(StrEnum):
    """Observed collision type identifiers."""

    PP = "p-p"
    P_PB = "p-Pb"
    PB_PB = "Pb-Pb"
    XE_XE = "Xe-Xe"
    COL_TYPE = "Col type"
    SEC_COL_TYPE = "Sec col type"
    TERT_COL_TYPE = "Tert col type"
    NE_NE = "NeNe"
    O_O = "OO"
    P_O = "pO"


class RepositoryType(StrEnum):
    """Observed repository type values."""

    CONF = "CONF"
    INT = "INT"
    PAP = "PAP"
    PUB = "PUB"


class PublicationType(StrEnum):
    """Observed publication type values (cross-references between record types)."""

    PAPER = "Paper"
    CONF_NOTE = "ConfNote"
    PUB_NOTE = "PubNote"
    ANALYSIS = "Analysis"


# Lenient type aliases — use these in model field annotations.
LenientMeetingType = _lenient(MeetingType)
LenientAnalysisPhase0State = _lenient(AnalysisPhase0State)
LenientPaperPhase1State = _lenient(PaperPhase1State)
LenientPaperPhase2State = _lenient(PaperPhase2State)
LenientPaperSubmissionState = _lenient(PaperSubmissionState)
LenientConfnotePhase1State = _lenient(ConfnotePhase1State)
LenientAnalysisStatus = _lenient(AnalysisStatus)
LenientPaperStatus = _lenient(PaperStatus)
LenientConfnoteStatus = _lenient(ConfnoteStatus)
LenientCollisionType = _lenient(CollisionType)
LenientRepositoryType = _lenient(RepositoryType)
LenientPublicationType = _lenient(PublicationType)
