"""
Markdown comes from:
https://www.notion.so/Query-Status-States-Mapping-349c4b623e3581c99e34fe2b78cc7248
"""

import re
from collections import defaultdict
from pathlib import Path

SECTION_RE = re.compile(
    r"^###\s+`(?P<key>[^`]+)`\s*(?:[^a-zA-Z]+\s*(?P<label>.+))?\s*$"
)
START = "# <AUTO-GENERATED-ENUMS:START>"
END = "# <AUTO-GENERATED-ENUMS:END>"

SKIP_ROW = {"---", "", "RAW_VALUE", "Raw Value"}

# -----------------------------
# parsing
# -----------------------------


def split_row(line: str) -> list[str]:
    return [p.strip() for p in line.strip().strip("|").split("|")]


def parse(md: str):
    tables = defaultdict(list)

    current_key = None
    current_variant = None

    for raw_line in md.splitlines():
        line = raw_line.strip()

        # ----------------------------
        # HEADER LINE ONLY
        # ----------------------------
        if line.startswith("###"):
            m = SECTION_RE.match(line)
            if m:
                current_key = m.group("key").strip()
                current_variant = (m.group("label") or "").strip() or None
            continue

        # ----------------------------
        # MUST BE INSIDE A TABLE
        # ----------------------------
        if not current_key or not line.startswith("|"):
            continue

        # skip markdown separator
        if set(line.replace("|", "").strip()) <= {"-"}:
            continue

        parts = split_row(line)
        if len(parts) < 2:
            continue

        raw = parts[0].strip()
        cols = parts[1:]

        tables[(current_key, current_variant)].append((raw, cols))

    return tables


# -----------------------------
# naming rules
# -----------------------------


def class_name(section: str, variant: str | None) -> str:
    base = "".join(x.capitalize() for x in section.split("."))

    if variant:
        v = variant.lower()

        if "paper" in v:
            return f"Paper{base}"
        if "confnote" in v or "conf" in v:
            return f"Confnote{base}"
        if "analysis" in v:
            return f"Analysis{base}"

    return base


def enum_name(raw: str) -> str:
    raw = raw.replace("`", "").strip()
    return re.sub(r"[^a-zA-Z0-9]+", "_", raw).upper()


def clean(value: str | None) -> str | None:
    if not value:
        return None
    v = value.strip()
    if v in SKIP_ROW or v == "—":
        return None
    return v


# -----------------------------
# build enum
# -----------------------------


def build_enum(name: str, items: list[tuple[str, str]]) -> str:
    if not items:
        return f"class {name}(StrEnum):\n    pass\n"

    out = [f"class {name}(StrEnum):", '    """Auto-generated enum."""', ""]

    for k, v in items:
        out.append(f'    {k} = "{v}"')

    return "\n".join(out)


# -----------------------------
# main generator
# -----------------------------


def generate(md: str) -> str:
    tables = parse(md)

    out = []

    for (section, variant), rows in tables.items():
        cname = class_name(section, variant)

        items = []

        for raw, cols in rows:
            if raw in SKIP_ROW:
                continue

            val = clean(cols[0] if cols else None)
            if not val:
                continue

            key = enum_name(raw)
            if key == "_":
                continue
            items.append((key, val))

        out.append(build_enum(cname, items))
        out.append("")

    return "\n".join(out)


# -----------------------------
# optional injector
# -----------------------------


def inject(file_path: str, content: str):
    text = Path(file_path).read_text()

    new_text, count = re.subn(
        rf"{re.escape(START)}.*?{re.escape(END)}",
        f"{START}\n{content}\n{END}",
        text,
        flags=re.DOTALL,
    )

    if count != 1:
        msg = f"inject: expected exactly one START/END marker block in {file_path!r}, found {count}"
        raise ValueError(msg)

    Path(file_path).write_text(new_text)


# -----------------------------
# CLI
# -----------------------------

if __name__ == "__main__":
    repo_root = Path(__file__).parent.parent
    statuses = repo_root / "externals" / "statuses.md"

    md_text = statuses.read_text()
    result = generate(md_text)

    output = repo_root / "src" / "stare" / "models" / "enums.py"
    inject(output, result)

    print(f"✔ Generated enums → {output}")
